---
kind: pipeline
type: docker
name: default

steps:
    - name: docker
      image: plugins/docker
      settings:
          repo: cell/czsh
          tag: "${DRONE_BRANCH/master/latest}"
          username:
              from_secret: docker_username
          password:
              from_secret: docker_password
