#!/bin/bash
#Provide the default parameters used by the image.

echo -n "docker run -ti --rm \
	-w \"\$PWD\" -v \"\$PWD\":\"\$PWD\" \
	-v /etc/localtime:/etc/localtime:ro \
	-v \$HOME/.ssh:\$HOME/.ssh:ro \
	-e USER -e UID=\$(id --user) -e GID=\$(id --group) \
	-v /var/run/docker.sock:/var/run/docker.sock \
	-e TERM \
	-e VIRTUAL_ENV=\$(basename \${0}) \
	-e COMPOSE_PROJECT_NAME \
	$@ \
	${DOCKER_IMAGE}"

