#!/bin/bash
#Provide the default parameters used by the image.

RO="\${HOME}/.ssh /etc/localtime"
RW="\${HOME}/.docker \${PWD} /dev/shm /run/user/\$(id --user) /var/run/docker.sock \${HOME}/.gnupg \${HOME}/.aws \${HOME}/.kube \${HOME}/.flyrc \${XDG_RUNTIME_DIR}/pulse/native \${HOME}/.config/pulse/cookie"
E="TERM XDG_RUNTIME_DIR"

echo -n "\
  ro_list=\"${RO}\"; rw_list=\"${RW}\"; e_list=\"${E}\"; \
  [[ -n \"\${DISPLAY}\"       ]] && e_list=\"\${e_list} DISPLAY\"       && rw_list=\"\${rw_list} /tmp/.X11-unix\"; \
  [[ -n \"\${XAUTHORITY}\"    ]] && e_list=\"\${e_list} XAUTHORITY\"    && ro_list=\"\${ro_list} \${XAUTHORITY}\"; \
  [[ -n \"\${SSH_AUTH_SOCK}\" ]] && e_list=\"\${e_list} SSH_AUTH_SOCK\" && ro_list=\"\${ro_list} \${SSH_AUTH_SOCK}\"; \

  ro_args=\"\"; for i in \${ro_list}; do [[ -e \"\${i}\" ]] && ro_args=\"\${ro_args} -v \${i}:\${i}:ro\"; done; \
  rw_args=\"\"; for i in \${rw_list}; do [[ -e \"\${i}\" ]] && rw_args=\"\${rw_args} -v \${i}:\${i}\"; done; \
  e_args=\"\";  for i in \${e_list};  do e_args=\"\${e_args} -e \${i}\"; done; \

  docker run -ti --rm \
    --net container:vpn --pid host \
    -w \"\$PWD\" \
    -e USER -e UID=\$(id --user) -e GID=\$(id --group) \
    -e CONTAINER_PROMPT=' vpn ' \
    \${ro_args} \${rw_args} \${e_args} \
    $@ \
    ${DOCKER_IMAGE}"
