#!/bin/bash
#Provide the default parameters used by the image.

RO="\${HOME}/.docker \${HOME}/.ssh /etc/localtime"
RW="\${PWD} /var/run/docker.sock \${HOME}/.aws \${HOME}/.kube"

echo -n "
  [[ -n \"\${DISPLAY}\"       ]] && display='-e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix' ;
  [[ -n \"\${SSH_AUTH_SOCK}\" ]] && ssh_sock=\"-e SSH_AUTH_SOCK -v \${SSH_AUTH_SOCK}:\${SSH_AUTH_SOCK}\" ;
  [[ \"\${PWD}\" != \"\${HOME}\" ]] && wd=\${PWD}; \
  home_dir=\$(find \${HOME} -maxdepth 1 -not -path '*/\.*' -not -path '.' -not -path \${HOME} | awk '{ printf(\"-v %s:%s \", \$0, \$0); }') ; \
  ro=\"\"; for i in ${RO}; do [[ -e \"\${i}\" ]] && ro=\"\${ro} -v \${i}:\${i}:ro\"; done; \
  rw=\"\"; for i in ${RW}; do [[ -e \"\${i}\" ]] && rw=\"\${rw} -v \${i}:\${i}\"; done; \

  docker run -ti --rm \
    --net host --pid host \
    -w \"\${PWD}\" -v \"\${wd}\":\"\${wd}\" \
    -e USER -e UID=\$(id --user) -e GID=\$(id --group) \
    -e TERM \
    -e VIRTUAL_ENV=\$(basename \${0}) \
    \${display:-} \
    \${ssh_sock:-} \
    \${home_dir:-} \
    \${ro} \${rw} \
    $@ \
    ${DOCKER_IMAGE}"
