#!/bin/bash

. /lib/stacktrace.sh

if [[ -e ~/.config/ntfy/client.yml ]]; then
    summary=${1:-}
    if [ -t 0 ]; then
        body="${2:-}"
    else
        body="${2:-$(< /dev/stdin)}"
    fi

    exec ntfy publish --title "${summary}" ${NTFY_TOPIC:-default} "${body}" >/dev/null
else
    exec /usr/bin/notify-send ${@}
fi
