#!/bin bash

set -evx
git push --set-upstream origin $(git rev-parse --abbrev-ref HEAD)

xdg-open "https://$(git config --get remote.origin.url | sed -e 's#^[^@]*@##' -e 's#:#/#' -e 's#\.git##')/compare/$(git rev-parse --abbrev-ref HEAD)?expand=1"
echo
