#!/bin/bash

# Inspired from https://github.com/brandon-rhodes/homedir/blob/master/bin/s

read -r -d '' rc <<-EOF

[[ -e ~/.profile ]] && source ~/.profile
[[ -e ~/.bash_profile ]] && source ~/.bash_profile

alias docker='sudo docker '
alias czsh='eval \$(docker run --rm --entrypoint cmd cell/czsh)'
alias me='eval \$(docker run --rm --entrypoint cmd-me cell/czsh)'
alias cvim='eval \$(docker run --rm --entrypoint cmd cell/cvim)'
alias playground='eval \$(docker run --rm --entrypoint cmd cell/playground)'

rc="\$(cat /dev/fd/3)"
function s {
    echo Connecting...
    ssh -t "$1" -- 'exec /bin/bash --rcfile /dev/fd/3 3<<<'$(printf %q "$rc")
}

EOF

exec ssh -t "$1" -- 'exec /bin/bash --rcfile /dev/fd/3 3<<<'$(printf %q "$rc")

