#!/bin/bash

git config user.email "$(git --no-pager log -1 --pretty=format:"%ae" HEAD)"
git config user.name  "$(git --no-pager log -1 --pretty=format:"%an" HEAD)"
git config push.default simple
git config core.excludesfile ~/.gitignore
echo  "$(git config user.name) <$(git config user.email)>"

