#!/bin/bash

# Inspired from https://github.com/brandon-rhodes/homedir/blob/master/bin/s

read -r -d '' rc <<-EOF

if docker images | grep 'cell/czsh.*latest' &>/dev/null; then
  eval \$(docker run --rm --entrypoint cmd-me cell/czsh -e CONTAINER_PROMPT=  )
  exit \$?
else
  echo 'cell/czsh not present'
fi

EOF

exec ssh -t "$1" -- 'exec /bin/bash --rcfile /dev/fd/3 3<<<'$(printf %q "$rc")

