#!/bin/bash

echo -e "echo $(cat ~/.ssh/*.pub) | sudo tee -a /home/ec2-user/.ssh/authorized_keys\n" | awsudo2 aws ssm start-session --target $@
echo "The shell has been a bit abused so it s normat to have an error like: \"Cannot perform start session: EOF\""

